version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mrudula_admin
      MONGO_INITDB_ROOT_PASSWORD: mrudula_password

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mrudula_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mrudula_password
      ME_CONFIG_MONGODB_URL: mongodb://mrudula_admin:mrudula_password@mongo:27017/
